name: Build AAB
on: push
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 17
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew bundleRelease
   
    - name: Build with Gradle
      run: ./gradlew packageRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
         name: app-release.apk
         path: app/build/outputs/apk/release/app-release.apk
         
    - name: Upload AAB Bundle
      uses: actions/upload-artifact@v2
      with:
         name: app-release.aab
         path: app/build/outputs/bundle/release/app-release.aab
